-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 12:44:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MYSPECTOR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MYSPECTOR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MYSPECTOR` DEFAULT CHARACTER SET utf8 ;
USE `MYSPECTOR` ;

-- -----------------------------------------------------
-- Table `MYSPECTOR`.`PIPELINES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MYSPECTOR`.`PIPELINES` ;

CREATE TABLE IF NOT EXISTS `MYSPECTOR`.`PIPELINES` (
  `ID_PIPELINE` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `TARGET_ID` INT NULL,
  PRIMARY KEY (`ID_PIPELINE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYSPECTOR`.`TARGET_HTTP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MYSPECTOR`.`TARGET_HTTP` ;

CREATE TABLE IF NOT EXISTS `MYSPECTOR`.`TARGET_HTTP` (
  `TARGET_ID` INT NOT NULL,
  `METHOD` ENUM('GET', 'POST', 'PUT', 'DELETE') NULL,
  `URI` VARCHAR(200) NULL,
  `VERSION` VARCHAR(5) NULL,
  `HEADERS` VARCHAR(1000) NULL,
  `CONTENT` VARCHAR(1000) NULL,
  PRIMARY KEY (`TARGET_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
